version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:latest
    container_name: reverse_proxy
    depends_on:
      - static-service
      - card-service
      - user-service
      - auth-service
      - market-service
    volumes:
      - ./Proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80

  # Static service
  static-service:
    image: alexispin/staticservice:latest
    container_name: static_service
    restart: on-failure

  # Card service
  card-service:
    image: alexispin/cardservice:latest
    container_name: card_service
    restart: on-failure

  # User service
  user-service:
    image: alexispin/userservice:latest
    container_name: user_service
    depends_on:
      - card-service
    restart: on-failure

  market-service:
    image: alexispin/marketservice:latest
    container_name: market_service
    depends_on:
      - card-service
      - user-service
    restart: on-failure

  auth-service:
    image: alexispin/loginservice:latest
    container_name: login_service
    restart: on-failure
